<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->projects() as $project) {
            Project::query()->updateOrCreate(
                ['slug' => $project['slug']],
                $project,
            );
        }
    }

    /**
     * @return array<int, array<string, array<int, string>|bool|int|string|null>>
     */
    private function projects(): array
    {
        return [
            [
                'title' => 'Orfa AI',
                'slug' => 'orfa-ai',
                'description' => 'Engineered a production-ready AI assistant platform for a USA client, combining a business-facing website, source-aware knowledge chat, session-based conversation tracking, admin analytics, and operational reporting within a scalable Laravel ecosystem.',
                'image_url' => 'https://api.example.com/storage/projects/orfa-ai.jpg',
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'OpenAI API',
                    'Redis',
                    'Docker',
                    'AWS',
                    'JWT',
                    'REST API',
                    'JavaScript',
                ],
                'live_url' => 'https://orfa.ai/',
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 1,
                'role' => 'Lead Laravel Backend Developer',
                'client_region' => 'USA',
                'problem' => 'The client needed a full AI assistant product that could serve SMB users through a professional web presence while also supporting source-based answers, session-aware chat history, user administration, analytics visibility, failed-response monitoring, and search intelligence.',
                'solution' => 'I developed the platform with Laravel using a modular backend architecture, secure API flows, AI-powered response handling, source-grounded chat support, session tracking, conversation history, dashboard analytics, user management, failed-query monitoring, top-search reporting, device tracking, peak-time analysis, and user feedback workflows.',
                'outcome' => 'Delivered a production-ready AI platform that gave the client a strong launch foundation, improved operational visibility, enabled ongoing chatbot optimization, and supported future scaling with a clean and extensible backend structure.',
                'confidential' => true,
            ],
            [
                'title' => 'Quins360 ERP',
                'slug' => 'quins360-erp',
                'description' => 'Engineered a modern ERP & HR management platform using Laravel and Vue.js, featuring employee lifecycle management, attendance tracking, task workflows, HR operations, finance modules, ticketing system, and real-time operational dashboards.',
                'image_url' => 'https://api.example.com/storage/projects/quins360.jpg',
                'technologies' => [
                    'Laravel',
                    'Vue.js',
                    'PHP',
                    'MySQL',
                    'REST API',
                    'JavaScript',
                    'Bootstrap',
                    'JWT Authentication',
                ],
                'live_url' => 'https://quins360.org/',
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 2,
                'role' => 'Lead Laravel Backend Developer',
                'client_region' => 'Bangladesh',
                'problem' => 'The organization needed an integrated ERP solution to replace fragmented manual processes across HR, employee tracking, task management, and finance operations, while ensuring real-time visibility and control.',
                'solution' => 'Designed and developed a modular ERP system with Laravel and Vue.js, implementing role-based authentication, employee management, attendance logging with time tracking, task and project workflows, HR modules, financial tracking, ticketing system, calendar scheduling, and dynamic dashboards. Focused on scalability, clean architecture, and seamless user experience.',
                'outcome' => 'Successfully delivered a scalable ERP platform that centralized business operations, enhanced team productivity, improved decision-making through real-time insights, and reduced operational inefficiencies.',
                'confidential' => false,
            ],
            [
                'title' => 'LawFix Platform',
                'slug' => 'lawfix-platform',
                'description' => 'Engineered a modern legal service marketplace platform enabling users to discover lawyers, explore legal categories, and access consultation services through a clean, responsive, and scalable Laravel-based system.',
                'image_url' => 'https://api.example.com/storage/projects/lawfix.jpg',
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'JavaScript',
                    'Bootstrap',
                    'REST API',
                ],
                'live_url' => 'https://lawfix.online/',
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 3,
                'role' => 'Lead Laravel Backend Developer',
                'client_region' => 'International',
                'problem' => 'The client needed a centralized legal platform where users could easily find qualified lawyers, browse categorized legal services, and connect with professionals without relying on scattered offline methods.',
                'solution' => 'Built the platform using Laravel with a modular architecture, implementing lawyer listing systems, category-based navigation, service modules, consultation flow, responsive UI, and scalable backend structure. Focused on usability, performance, and clean data organization to support future growth.',
                'outcome' => 'Successfully delivered a professional legal marketplace platform that improved service accessibility, increased engagement between clients and lawyers, and established a scalable base for future expansion.',
                'confidential' => false,
            ],
            [
                'title' => 'QuinsAid Fundraising Platform',
                'slug' => 'quinsaid-platform',
                'description' => 'Built a scalable fundraising and donation ecosystem using Laravel, combining campaign management, donation processing, event systems, course modules, and real-time analytics into a unified platform for global impact initiatives.',
                'image_url' => 'https://api.example.com/storage/projects/quinsaid.jpg',
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'JavaScript',
                    'Bootstrap',
                    'REST API',
                    'Payment Gateway Integration',
                ],
                'live_url' => 'https://quinsaid.com/',
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 4,
                'role' => 'Lead Laravel Backend Developer',
                'client_region' => 'UK',
                'problem' => 'The organization required a robust digital platform to manage global fundraising initiatives, including donation tracking, campaign lifecycle management, user engagement, event coordination, and financial transparency across multiple regions.',
                'solution' => 'Architected and developed the platform using Laravel with a modular backend structure, implementing donation systems, campaign workflows, event management, course modules, admin dashboards, transaction logs, analytics reporting, and role-based access control. Designed the system to ensure scalability, maintainability, and real-time operational visibility.',
                'outcome' => 'Successfully delivered a production-ready fundraising platform that enhanced global donation accessibility, improved operational transparency, and provided a strong technical foundation for scaling impact-driven initiatives.',
                'confidential' => false,
            ],
            [
                'title' => 'Superman4U Marketplace',
                'slug' => 'superman4u-marketplace',
                'description' => 'Developed an on-demand service marketplace platform enabling users to discover, book, and manage services across multiple categories with a scalable Laravel-based backend.',
                'image_url' => 'https://api.example.com/storage/projects/superman4u.jpg',
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'JavaScript',
                    'Bootstrap',
                    'REST API',
                ],
                'live_url' => 'https://superman4u.com/',
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 5,
                'role' => 'Lead Laravel Backend Developer',
                'client_region' => 'International',
                'problem' => 'The client needed a centralized platform to connect customers with service providers, replacing scattered service discovery methods and enabling structured booking and service management.',
                'solution' => 'Built the platform using Laravel with a modular architecture, implementing service listings, category-based browsing, booking workflows, provider onboarding, review systems, and user dashboards. Focused on scalability, clean API design, and smooth user experience.',
                'outcome' => 'Delivered a production-ready service marketplace that streamlined service discovery, improved booking efficiency, and provided a scalable foundation for future growth and expansion.',
                'confidential' => false,
            ],
            [
                'title' => 'HireTrack ATS',
                'slug' => 'hiretrack-ats',
                'description' => 'Engineered recruiting workflows for candidate pipelines, interview scheduling, notes, and role-based access control.',
                'image_url' => 'https://api.example.com/storage/projects/hiretrack-ats.jpg',
                'technologies' => ['Laravel', 'Sanctum', 'MySQL', 'Docker', 'Mailhog'],
                'live_url' => 'https://hiretrack.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 6,
                'role' => 'Full-Stack Laravel Developer',
                'client_region' => 'Germany',
                'problem' => 'Recruiters needed a customizable hiring system without the complexity of enterprise ATS products.',
                'solution' => 'Delivered modular APIs for candidates, interviews, feedback loops, and secure permissions.',
                'outcome' => 'Streamlined hiring collaboration for distributed recruiting teams.',
                'confidential' => false,
            ],
            [
                'title' => 'TravelMate Booking',
                'slug' => 'travelmate-booking',
                'description' => 'Built booking and itinerary APIs for a travel platform with package management, payment integration, and admin tools.',
                'image_url' => 'https://api.example.com/storage/projects/travelmate-booking.jpg',
                'technologies' => ['Laravel', 'Stripe', 'Redis', 'Docker', 'AWS RDS'],
                'live_url' => 'https://travelmate.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 7,
                'role' => 'Backend Developer',
                'client_region' => 'Singapore',
                'problem' => 'Manual booking operations were slowing down customer response times.',
                'solution' => 'Automated package booking, payments, and itinerary generation with a clean admin API.',
                'outcome' => 'Cut operational delays and improved booking throughput.',
                'confidential' => false,
            ],
            [
                'title' => 'PropertyHub CRM',
                'slug' => 'propertyhub-crm',
                'description' => 'Developed CRM APIs for real estate teams to manage listings, leads, follow-ups, and regional performance reporting.',
                'image_url' => 'https://api.example.com/storage/projects/propertyhub-crm.jpg',
                'technologies' => ['Laravel', 'PostgreSQL', 'Redis', 'Docker', 'Metabase'],
                'live_url' => null,
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 8,
                'role' => 'Senior Software Engineer',
                'client_region' => 'Bangladesh',
                'problem' => 'Agents needed a shared system for lead management and listing workflows.',
                'solution' => 'Created APIs for listing lifecycle management, lead assignment, and sales reporting.',
                'outcome' => 'Improved coordination and follow-up consistency across sales teams.',
                'confidential' => true,
            ],
            [
                'title' => 'SupportDesk Pro',
                'slug' => 'supportdesk-pro',
                'description' => 'Created customer support ticketing APIs with SLA tracking, internal notes, canned replies, and performance reporting.',
                'image_url' => 'https://api.example.com/storage/projects/supportdesk-pro.jpg',
                'technologies' => ['Laravel', 'MySQL', 'Redis', 'Queues', 'Docker'],
                'live_url' => 'https://supportdesk.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 9,
                'role' => 'Backend Engineer',
                'client_region' => 'Netherlands',
                'problem' => 'The support team needed a system to manage response times and workload distribution.',
                'solution' => 'Implemented ticket workflows, SLA timers, automation hooks, and searchable audit trails.',
                'outcome' => 'Improved support team responsiveness and issue visibility.',
                'confidential' => false,
            ],
            [
                'title' => 'FinScope Dashboard',
                'slug' => 'finscope-dashboard',
                'description' => 'Built a finance operations dashboard backend with transaction feeds, alerting, user permissions, and portfolio summaries.',
                'image_url' => 'https://api.example.com/storage/projects/finscope-dashboard.jpg',
                'technologies' => ['Laravel', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
                'live_url' => null,
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 10,
                'role' => 'Senior Laravel Engineer',
                'client_region' => 'USA',
                'problem' => 'Finance teams needed near-real-time operational visibility without spreadsheet-driven reporting.',
                'solution' => 'Designed resilient APIs for dashboard widgets, alerts, and filtered reporting.',
                'outcome' => 'Delivered a stable reporting backbone for internal finance operations.',
                'confidential' => true,
            ],
        ];
    }
}
