<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->projects() as $project) {
            Project::query()->updateOrCreate(
                ['slug' => $project['slug']],
                $project,
            );
        }
    }

    /**
     * @return array<int, array<string, array<int, string>|bool|int|string|null>>
     */
    private function projects(): array
    {
        return [
            [
                'title' => 'Orfa AI',
                'slug' => 'orfa-ai',
                'description' => 'Engineered a production-ready AI assistant platform for a USA client, combining a business-facing website, source-aware knowledge chat, session-based conversation tracking, admin analytics, and operational reporting within a scalable Laravel ecosystem.',
                'image_url' => 'https://api.example.com/storage/projects/orfa-ai.jpg',
                'technologies' => [
                    'Laravel',
                    'PHP',
                    'MySQL',
                    'OpenAI API',
                    'Redis',
                    'Docker',
                    'AWS',
                    'JWT',
                    'REST API',
                    'JavaScript'
                ],
                'live_url' => 'https://orfa.ai/',
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 1,
                'role' => 'Lead Laravel Backend Developer',
                'client_region' => 'USA',
                'problem' => 'The client needed a full AI assistant product that could serve SMB users through a professional web presence while also supporting source-based answers, session-aware chat history, user administration, analytics visibility, failed-response monitoring, and search intelligence.',
                'solution' => 'I developed the platform with Laravel using a modular backend architecture, secure API flows, AI-powered response handling, source-grounded chat support, session tracking, conversation history, dashboard analytics, user management, failed-query monitoring, top-search reporting, device tracking, peak-time analysis, and user feedback workflows.',
                'outcome' => 'Delivered a production-ready AI platform that gave the client a strong launch foundation, improved operational visibility, enabled ongoing chatbot optimization, and supported future scaling with a clean and extensible backend structure.',
                'confidential' => true,
            ],
            [
                'title' => 'MedCare Connect',
                'slug' => 'medcare-connect',
                'description' => 'Created a healthcare appointment and patient communication platform with doctor scheduling, notifications, and audit-friendly APIs.',
                'image_url' => 'https://api.example.com/storage/projects/medcare-connect.jpg',
                'technologies' => ['Laravel', 'MySQL', 'Twilio', 'Vue', 'Docker'],
                'live_url' => null,
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 2,
                'role' => 'Backend Lead',
                'client_region' => 'Canada',
                'problem' => 'The client needed a reliable patient scheduling system with secure communication records.',
                'solution' => 'Built REST APIs for appointments, doctor availability, reminders, and activity tracking.',
                'outcome' => 'Reduced scheduling friction and improved communication reliability across clinics.',
                'confidential' => true,
            ],
            [
                'title' => 'ShipFlow ERP',
                'slug' => 'shipflow-erp',
                'description' => 'Developed logistics and warehouse management APIs covering shipment tracking, invoicing, dispatch flows, and reporting.',
                'image_url' => 'https://api.example.com/storage/projects/shipflow-erp.jpg',
                'technologies' => ['Laravel', 'PostgreSQL', 'Redis', 'Docker', 'Nginx'],
                'live_url' => null,
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 3,
                'role' => 'Senior Backend Engineer',
                'client_region' => 'UAE',
                'problem' => 'Operations teams were juggling shipment data across disconnected spreadsheets and tools.',
                'solution' => 'Centralized fulfillment workflows into a single Laravel API platform with real-time status updates.',
                'outcome' => 'Improved shipment visibility and reduced operational overhead.',
                'confidential' => true,
            ],
            [
                'title' => 'EduMentor LMS',
                'slug' => 'edumentor-lms',
                'description' => 'Built an online learning platform with course APIs, instructor tools, progress tracking, and subscription billing integrations.',
                'image_url' => 'https://api.example.com/storage/projects/edumentor-lms.jpg',
                'technologies' => ['Laravel', 'Stripe', 'MySQL', 'Queue Jobs', 'AWS S3'],
                'live_url' => 'https://edumentor.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 4,
                'role' => 'Laravel Developer',
                'client_region' => 'UK',
                'problem' => 'The platform needed stable APIs for courses, subscriptions, and student progress.',
                'solution' => 'Implemented structured course modules, checkout flows, and asynchronous content-processing jobs.',
                'outcome' => 'Enabled instructors to scale digital course delivery with less manual work.',
                'confidential' => false,
            ],
            [
                'title' => 'RetailPulse Analytics',
                'slug' => 'retailpulse-analytics',
                'description' => 'Created a retail insights dashboard backend that aggregated product, sales, and customer behavior data into actionable reports.',
                'image_url' => 'https://api.example.com/storage/projects/retailpulse-analytics.jpg',
                'technologies' => ['Laravel', 'PostgreSQL', 'Chart APIs', 'Redis', 'AWS EC2'],
                'live_url' => null,
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 5,
                'role' => 'API Engineer',
                'client_region' => 'Australia',
                'problem' => 'The client lacked consolidated reporting across multiple sales channels.',
                'solution' => 'Built aggregation pipelines and reporting endpoints tailored for management dashboards.',
                'outcome' => 'Helped leadership make faster inventory and campaign decisions.',
                'confidential' => true,
            ],
            [
                'title' => 'HireTrack ATS',
                'slug' => 'hiretrack-ats',
                'description' => 'Engineered recruiting workflows for candidate pipelines, interview scheduling, notes, and role-based access control.',
                'image_url' => 'https://api.example.com/storage/projects/hiretrack-ats.jpg',
                'technologies' => ['Laravel', 'Sanctum', 'MySQL', 'Docker', 'Mailhog'],
                'live_url' => 'https://hiretrack.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 6,
                'role' => 'Full-Stack Laravel Developer',
                'client_region' => 'Germany',
                'problem' => 'Recruiters needed a customizable hiring system without the complexity of enterprise ATS products.',
                'solution' => 'Delivered modular APIs for candidates, interviews, feedback loops, and secure permissions.',
                'outcome' => 'Streamlined hiring collaboration for distributed recruiting teams.',
                'confidential' => false,
            ],
            [
                'title' => 'TravelMate Booking',
                'slug' => 'travelmate-booking',
                'description' => 'Built booking and itinerary APIs for a travel platform with package management, payment integration, and admin tools.',
                'image_url' => 'https://api.example.com/storage/projects/travelmate-booking.jpg',
                'technologies' => ['Laravel', 'Stripe', 'Redis', 'Docker', 'AWS RDS'],
                'live_url' => 'https://travelmate.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 7,
                'role' => 'Backend Developer',
                'client_region' => 'Singapore',
                'problem' => 'Manual booking operations were slowing down customer response times.',
                'solution' => 'Automated package booking, payments, and itinerary generation with a clean admin API.',
                'outcome' => 'Cut operational delays and improved booking throughput.',
                'confidential' => false,
            ],
            [
                'title' => 'PropertyHub CRM',
                'slug' => 'propertyhub-crm',
                'description' => 'Developed CRM APIs for real estate teams to manage listings, leads, follow-ups, and regional performance reporting.',
                'image_url' => 'https://api.example.com/storage/projects/propertyhub-crm.jpg',
                'technologies' => ['Laravel', 'PostgreSQL', 'Redis', 'Docker', 'Metabase'],
                'live_url' => null,
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 8,
                'role' => 'Senior Software Engineer',
                'client_region' => 'Bangladesh',
                'problem' => 'Agents needed a shared system for lead management and listing workflows.',
                'solution' => 'Created APIs for listing lifecycle management, lead assignment, and sales reporting.',
                'outcome' => 'Improved coordination and follow-up consistency across sales teams.',
                'confidential' => true,
            ],
            [
                'title' => 'SupportDesk Pro',
                'slug' => 'supportdesk-pro',
                'description' => 'Created customer support ticketing APIs with SLA tracking, internal notes, canned replies, and performance reporting.',
                'image_url' => 'https://api.example.com/storage/projects/supportdesk-pro.jpg',
                'technologies' => ['Laravel', 'MySQL', 'Redis', 'Queues', 'Docker'],
                'live_url' => 'https://supportdesk.example.com',
                'github_url' => null,
                'featured' => false,
                'published' => true,
                'sort_order' => 9,
                'role' => 'Backend Engineer',
                'client_region' => 'Netherlands',
                'problem' => 'The support team needed a system to manage response times and workload distribution.',
                'solution' => 'Implemented ticket workflows, SLA timers, automation hooks, and searchable audit trails.',
                'outcome' => 'Improved support team responsiveness and issue visibility.',
                'confidential' => false,
            ],
            [
                'title' => 'FinScope Dashboard',
                'slug' => 'finscope-dashboard',
                'description' => 'Built a finance operations dashboard backend with transaction feeds, alerting, user permissions, and portfolio summaries.',
                'image_url' => 'https://api.example.com/storage/projects/finscope-dashboard.jpg',
                'technologies' => ['Laravel', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
                'live_url' => null,
                'github_url' => null,
                'featured' => true,
                'published' => true,
                'sort_order' => 10,
                'role' => 'Senior Laravel Engineer',
                'client_region' => 'USA',
                'problem' => 'Finance teams needed near-real-time operational visibility without spreadsheet-driven reporting.',
                'solution' => 'Designed resilient APIs for dashboard widgets, alerts, and filtered reporting.',
                'outcome' => 'Delivered a stable reporting backbone for internal finance operations.',
                'confidential' => true,
            ],
        ];
    }
}
